baseurl = "http://barbery.me/"
languageCode = "zh-CN"
Title = "Barbery's Blog"
HasCJKLanguage = true
Theme = "hugo-pacman-theme"
pygmentsStyle = "default"
pygmentsUseClasses = true
RSSUri = "feed.xml"
Paginate = 10
disablePathToLower = true
filename_case = 0

[permalinks]
  post = "/:section/:filename"

[Author]
  Name = "barbery"

[Params]
  AuthorHomepage = "http://barbery.me"
  #BottomIntroduce = "Introduce1 <br/> Introduce2"
  Description = ""
  Subtitle = "夫君子之行，静以修身，俭以养德。非淡泊无以明志，非宁静无以致远。夫学须静也，才须学也"
  Weibo = "stutostu"
  GitHub = "Barbery"
  LinkIn = "BarberyXie"
#  Imglogo = "img/logo.svg"
#  AuthorImg = "img/author.jpg"
  DateFormat = "2006年01月02日"
  MonthFormat = "2006年01月"
  FancyBox = true

  #[Params.DuoShuo]
  #  ShortName = "coderzh"

  [Params.Disqus]
    ShortName = "barbery"

  [Params.GoogleAnalytics]
    ID = "UA-80280597-1"

  [Params.Strings]
    Search = "search"
    PageNotFound = "你访问的页面不存在"
    ShowSideBar = "显示侧边栏"
    HideSideBar = "隐藏侧边栏"
    Categories = "分类"
    Archive = "归档"
    Tags = "标签"
    TagCloud = "标签云"
    Rss = "RSS 订阅"
    TableOfContents = "文章目录"

[Menu]
  [[Menu.Main]]
    Name = "home"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "about"
    URL = "/about"
    Weight = 2
  [[Menu.Main]]
    Name = "link"
    URL = "/link"
    Weight = 3